from crEnvironmentSal import init_environment_sal

from crEnvironmentSal import get_preprocessed_environment
from crEnvironmentSal import get_catalog_chm_file_full_path

from crEnvironmentSal import get_root_output_folder_full_path
from crEnvironmentSal import get_catalog_html_output_full_path